CREATE STREAM SOURCE_PRODUCTS WITH (KAFKA_TOPIC='xe.STORE.PRODUCTS', VALUE_FORMAT='AVRO');
CREATE STREAM SOURCE_CUSTOMERS WITH (KAFKA_TOPIC='xe.STORE.CUSTOMERS', VALUE_FORMAT='AVRO');
CREATE STREAM SOURCE_ORDERS WITH (KAFKA_TOPIC='xe.STORE.ORDERS', VALUE_FORMAT='AVRO');
CREATE STREAM SOURCE_ORDER_ITEMS WITH (KAFKA_TOPIC='xe.STORE.ORDER_ITEMS', VALUE_FORMAT='AVRO');

CREATE STREAM TARGET_ORDER_ITEMS WITH (KAFKA_TOPIC='target_order_items', VALUE_FORMAT='AVRO')
AS SELECT 'order_items::'+ CAST(ORDERID AS VARCHAR) + '::' +  CAST(ITEMID AS VARCHAR) KEY,
CAST(ORDERID AS VARCHAR) AS "orderId",
CAST(ITEMID AS VARCHAR) AS "itemId",
CAST(PRODUCTID AS VARCHAR) AS "productId",
CAST(QUANTITY AS INTEGER) AS "quantity",
ROUND(PRICE,2) AS "price"
FROM SOURCE_ORDER_ITEMS
EMIT CHANGES;

CREATE STREAM TARGET_ORDERS WITH (KAFKA_TOPIC='target_orders', VALUE_FORMAT='AVRO')
AS SELECT 'order::'+ CAST(ORDERID AS VARCHAR)  KEY,
CAST(ORDERID AS VARCHAR) AS "orderId", CAST(CUSTOMERID AS VARCHAR) AS "customerId",
CAST(ORDERSTATUS AS VARCHAR) AS "orderStatus",
ORDERDATE AS "orderDate"
FROM SOURCE_ORDERS
EMIT CHANGES;

CREATE STREAM TARGET_CUSTOMERS WITH (KAFKA_TOPIC='target_customers', VALUE_FORMAT='AVRO')
AS SELECT 'customer::'+ CAST(CUSTOMERID AS VARCHAR)  KEY,
CAST(CUSTOMERID AS VARCHAR) AS "customerId", FIRSTNAME AS "firstName",
LASTNAME AS "lastName", PHONE AS "phone", EMAIL AS "email" ,
ADDRESS AS "address" FROM SOURCE_CUSTOMERS
EMIT CHANGES;

CREATE STREAM TARGET_PRODUCTS WITH (KAFKA_TOPIC='target_products', VALUE_FORMAT='AVRO')
AS SELECT 'product::'+ CAST(PRODUCTID AS VARCHAR)  KEY,
CAST(PRODUCTID AS VARCHAR) AS "productId", PRODUCTNAME AS "productName",
DESCRIPTION AS "description",
ROUND(PRICE,2) AS "price" FROM SOURCE_PRODUCTS
EMIT CHANGES;